version: 2
updates:
  - package-ecosystem: "composer"
    open-pull-requests-limit: 5
    directory: "/"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    open-pull-requests-limit: 5
    directory: "/"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: "weekly"
